# Generated by Django 5.0.1 on 2024-01-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_services_name_alter_services_price_scheduling'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduling',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário'),
        ),
    ]
