# Generated by Django 5.0.1 on 2024-01-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_services_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Barbeiro(a)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='foto_barbeiro')),
            ],
        ),
    ]
