# Generated by Django 5.0.1 on 2024-01-05 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_team'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='BarbersTeam',
        ),
    ]
