# Generated by Django 5.0.1 on 2024-01-05 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_team_barbersteam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barbersteam',
            options={'verbose_name_plural': 'Barbers Team'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name_plural': 'Services'},
        ),
        migrations.AddField(
            model_name='scheduling',
            name='barber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.barbersteam'),
        ),
    ]
