# Generated by Django 5.0.1 on 2024-01-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_barbersteam_options_alter_services_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduling',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Celular'),
        ),
    ]
