# Generated by Django 5.0.1 on 2024-01-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_scheduling_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduling',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Celular'),
        ),
    ]
