# Generated by Django 5.0.1 on 2024-01-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_scheduling_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('image_portfolio', models.ImageField(blank=True, null=True, upload_to='portifólio')),
            ],
        ),
    ]
