# Generated by Django 5.0.1 on 2024-01-08 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image_portfolio',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
