# Generated by Django 5.0.1 on 2024-01-09 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_portfolio_image_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, null=True)),
                ('scheduling', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.scheduling', verbose_name='Todos os Agendamentos:')),
            ],
        ),
    ]
