# Generated by Django 5.0.1 on 2024-01-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_finance'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduling',
            name='quantity_service_completed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduling',
            name='scheduling_service_completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
