# Generated by Django 5.0.1 on 2024-01-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_scheduling_quantity_service_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduling',
            name='quantity_service_completed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
