# Generated by Django 5.0.1 on 2024-01-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_scheduling_quantity_service_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduling',
            name='quantity_service_completed',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
