# Generated by Django 5.0.1 on 2024-01-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_scheduling_quantity_service_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduling',
            name='quantity_service_completed',
        ),
        migrations.RemoveField(
            model_name='scheduling',
            name='scheduling_service_completed',
        ),
        migrations.AlterField(
            model_name='services',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Preço'),
        ),
    ]
