# Generated by Django 5.0.1 on 2024-01-09 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_services_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduling',
            name='scheduling_complete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='scheduling',
            name='scheduling_quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='service',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.services', verbose_name='Serviço'),
        ),
    ]
