# Generated by Django 5.0.1 on 2024-01-11 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_scheduling_scheduling_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_carrousel', models.ImageField(blank=True, null=True, upload_to='carrousel_images')),
                ('title_carousel', models.CharField(blank=True, max_length=255, null=True, verbose_name='Título do Carrousel:')),
            ],
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='scheduling_quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.services', verbose_name='Serviço'),
        ),
    ]
