# Generated by Django 5.0.1 on 2024-01-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_carrousel_alter_scheduling_scheduling_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
