# Generated by Django 5.0.1 on 2024-01-15 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_pix_scheduling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pix',
            name='user',
        ),
    ]
