# Generated by Django 5.0.1 on 2024-01-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_remove_pix_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduling',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Pago'),
        ),
    ]
