# Generated by Django 5.0.1 on 2024-01-23 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_scheduling_paid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carrousel',
        ),
        migrations.DeleteModel(
            name='Pix',
        ),
    ]
